# Generated by Django 4.0.10 on 2024-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_article_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_no'], name='core_articl_article_1c23c0_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_no', 'price'], name='core_articl_article_73c613_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['price'], name='core_articl_price_4061ad_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['provider_no'], name='core_articl_provide_cc843a_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['provider_no'], name='core_provid_provide_fb4c98_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['provider_name'], name='core_provid_provide_180222_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['provider_no', 'provider_name'], name='core_provid_provide_c098b3_idx'),
        ),
    ]
